### ISSUE TITLE
Implement parsing of union types and adjust syntax

### ISSUE THREAD

**Issue by alexrp** [vezel-dev/celerity#21]
This is currently completely missing. Same for the AST representation.

https://github.com/vezel-dev/celerity/blob/e9819a046c42f68cdec3c1261483e705be36cfe6/doc/language/syntactic-structure/types.md?plain=1#L3-L26

**Comment by alexrp** [comment]
This will require language changes. The current type grammar is ambiguous. For example, what does `fn() -> int or real` mean?

**Comment by Roukanken42** [comment]
Altering grammar to 
```ebnf
type ::= primary-type ('or' (primary-type | function-type) )*

return-type ::= none-type |
                primary-type |
                function-type

primary-type ::= any-type | 
                 literal-type | 
                 boolean-type | 
                 integer-type | 
                 real-type | 
                 atom-type | 
                 string-type | 
                 reference-type | 
                 handle-type | 
                 module-type | 
                 record-type | 
                 error-type | 
                 tuple-type | 
                 array-type | 
                 set-type | 
                 map-type | 
                 agent-type | 
                 nominal-type |
                 '(' type ')'
```
should remove the unambiguousness with minimal changes to structure of code.

This equals to banning directly having a `fn` on lhs of `or`, and banning direct `or` as return of function. For ability to express such types, a parenthesized type is added.
